apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
spec:
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
      - image: okteto.dev/python-ocr-api:1.0.0
        name: ocr

---

apiVersion: v1
kind: Service
metadata:
  name: ocr
spec:
  type: ClusterIP
  ports:
  - name: "ocr"
    port: 9898
  selector:
    app: ocr

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocr
  annotations:
    dev.okteto.com/generate-host: ocr
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: ocr
                port:
                  number: 9898
            path: /
            pathType: ImplementationSpecific
