apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-api
spec:
  selector:
    matchLabels:
      app: ocr-api
  template:
    metadata:
      labels:
        app: ocr-api
    spec:
      containers:
      - image: okteto.dev/python-ocr-api:1.0.0
        name: ocr-api

---

apiVersion: v1
kind: Service
metadata:
  name: ocr-api
spec:
  type: ClusterIP
  ports:
  - name: "ocr-api"
    port: 8080
  selector:
    app: ocr-api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocr-api
  annotations:
    dev.okteto.com/generate-host: ocr-api
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: ocr-api
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
